services:
  frontend:
    build:
      context: .
      target: dev
    ports:
      - "3000:5998"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    working_dir: /app/frontend
    command: sh -c "npm install && npm run dev"

  backend:
    build:
      context: .
      target: dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    working_dir: /app/backend
    command: sh -c "npm install && npm run dev"